### ISSUE TITLE
Empty Text Box

### ISSUE THREAD

**Issue by EmekaEnshinyan** [EmekaEnshinyan/Task-Manager-App#2]
Text remains when task is added. Text must be cleared upon push of "Add Task" button.

**Comment by EmekaEnshinyan** [comment]
Yeah, looks quite ugly. We need it fixed!!

**Comment by EmekaEnshinyan** [comment]
I have (what feels like) a roundabout solution: add another useState Hook.

App.jsx>
 const [tasks, setTasks] = useState([]); 
 _**const [textBox, setTextBox] = useState("");**_ 
const handleSubmitTask = (e) => {
.
.
.
**_setTextBox("");_** 

return (
.
.
<input
            type="text"
            name="addTask"
            id="addTask"
            className="border border-blue-500"
            **_value={textBox}
            onChange={(e) => setTextBox(e.target.value)}_**

**Comment by wayatonmetric** [comment]
worked on this some but with the way it prevents default from propagating I cant get it to propagate correctly yet with out it either empty out text box and not setting values into array or visa versa. So still working on it. I thought about reverting it to set values but with react if you add value="empty" it the textbox stops accepting any values.

**Comment by EmekaEnshinyan** [comment]
Copy that. I'll take a look at it again when I have time.

I'll need to be more thorough in testing the app next time. 

P.S. I've never written test units for js. I've used Junit and Python's unittest. I hope it won't be terribly different.

**Comment by wayatonmetric** [comment]
https://www.selenium.dev/documentation/webdriver/
this program scraps and loads website like a user for testing I can write some scripts I have used this program before.

**Comment by wayatonmetric** [comment]
https://www.selenium.dev/downloads/
